//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichdat
    {
        public string MaDatSan { get; set; }
        public string MaKhachHang { get; set; }
        public string masan { get; set; }
        public Nullable<System.DateTime> TGianBatDau { get; set; }
        public Nullable<System.DateTime> TGianKetThuc { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual san san { get; set; }
    }
}
